### ISSUE TITLE
Audit new site

### ISSUE THREAD

**Issue by jtremback** [althea-mesh/althea-site-deluxe#4]
- Broken links
- Other broken stuff
- Chrome audits on site loading etc
- Images are a bit over optimized

deadline:10/22/2018

**Comment by asoltys** [comment]
Ran https://validator.w3.org/checklink?uri=althea.org&hide_type=all&depth=&check=Check and all looks good. Also went through the chrome audit tool and fixed a few things like alt tags, meta tags, title attributes, etc. There were a few things it suggested like using http/2 and increasing the cache expiry time that require modifying http response headers from the server which isn't possible if we're hosting on gh-pages. 

The main thing I accomplished was converting images to webp to get filesizes down and putting in fallback mechanisms for browsers that don't support it yet.
