### ISSUE TITLE
Updates to new site

### ISSUE THREAD

**Issue by jtremback** [althea-mesh/althea-site-deluxe#6]
According to this doc: https://althea.quip.com/25lbAaqjcYgV/Website-update-instructions-102218

deadline:10/24/2018

**Comment by asoltys** [comment]
Implemented by https://github.com/althea-mesh/althea-site-deluxe/commit/b32573674f3a46f7f1ea4fbb9d6b549fcf33512f and https://github.com/althea-mesh/althea-site-deluxe/commit/ed1b94b9bafbdee089a8bccd119854484c0a7916
